package com.oyuki.notification.enums;

public enum NotificationType {

    ORDER_PLACED,
    NEW_ORDER_RECEIVED,
    PROVIDER_ACCEPTED,
    PROVIDER_REJECTED,

    RIDER_ASSIGNED,
    ORDER_PICKED_UP,
    OUT_FOR_DELIVERY,
    ORDER_DELIVERED,

    PAYMENT_PROOF_SUBMITTED,
    PAYMENT_CONFIRMED,
    PAYMENT_REJECTED,

    FARMERS_DAY_ANNOUNCEMENT,
    FARMERS_DAY_REMINDER,
    FARMERS_DAY_STARTED,

    SYSTEM_ANNOUNCEMENT,
    REFUND_CREATED,
REFUND_PROCESSING,
REFUND_COMPLETED,
REFUND_FAILED,
REFUND_CANCELLED,
ORDER_CANCELLED,
}