package com.oyuki.admin.service;

import com.oyuki.admin.dto.AdminMarketerResponse;
import com.oyuki.admin.dto.CreateMarketerRequest;
import com.oyuki.auth.entity.VerificationToken;
import com.oyuki.auth.repository.VerificationTokenRepository;
import com.oyuki.auth.service.OtpDeliveryService;
import com.oyuki.common.util.OtpGenerator;
import com.oyuki.referral.service.ReferralService;
import com.oyuki.user.entity.User;
import com.oyuki.user.enums.AccountStatus;
import com.oyuki.user.enums.Role;
import com.oyuki.user.repository.UserRepository;

import lombok.RequiredArgsConstructor;

import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Locale;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class AdminMarketerService {

    private final UserRepository userRepository;
    private final VerificationTokenRepository tokenRepository;
    private final PasswordEncoder passwordEncoder;
    private final OtpGenerator otpGenerator;
    private final OtpDeliveryService otpDeliveryService;
    private final ReferralService referralService;

    @Transactional
    public AdminMarketerResponse create(CreateMarketerRequest request) {

        String email = cleanEmail(request.email());
        String phone = cleanPhone1(request.phoneNumber());

        if (email == null && phone == null) {
            throw new IllegalArgumentException(
                    "At least an email address or phone number is required"
            );
        }

        if (email != null && userRepository.existsByEmailIgnoreCase(email)) {
            throw new IllegalArgumentException(
                    "This email address is already registered"
            );
        }

        if (phone != null && userRepository.existsByPhoneNumber(phone)) {
            throw new IllegalArgumentException(
                    "This phone number is already registered"
            );
        }

        User marketer = User.builder()
                .fullName(request.fullName().trim())
                .email(email)
                .phoneNumber(phone)
                .passwordHash(
                        passwordEncoder.encode(
                                UUID.randomUUID().toString()
                        )
                )
                .role(Role.MARKETER)
                .status(AccountStatus.PENDING_VERIFICATION)
                .emailVerified(false)
                .phoneVerified(false)
                .build();

        marketer = userRepository.save(marketer);

        // Generate the marketer's referral code.
        referralService.ensureReferralCode(marketer);

        /*
         * Generate an email OTP.
         *
         * The phone OTP is generated by Twilio Verify,
         * so we only generate/store the email OTP locally.
         */
        if (email != null) {

            String emailOtp =
                    otpGenerator.generateSixDigitOtp();

            VerificationToken token =
                    VerificationToken.builder()
                            .user(marketer)
                            .tokenHash(
                                    passwordEncoder.encode(emailOtp)
                            )
                            .expiresAt(
                                    LocalDateTime.now()
                                            .plusMinutes(10)
                            )
                            .used(false)
                            .attempts(0)
                            .build();

            tokenRepository.save(token);

            otpDeliveryService.sendAdminActivationOtps(
                    marketer,
                    emailOtp
            );

        } else {

            /*
             * No email was supplied.
             * sendAdminActivationOtps must therefore
             * send the OTP through SMS only.
             */
            otpDeliveryService.sendAdminActivationOtps(
                    marketer,
                    null
            );
        }

        return AdminMarketerResponse.from(marketer);
    }

    @Transactional(readOnly = true)
    public List<AdminMarketerResponse> list() {

        return userRepository
                .findAllByRole(Role.MARKETER)
                .stream()
                .map(AdminMarketerResponse::from)
                .toList();
    }

    private String cleanEmail(String value) {

        if (value == null || value.isBlank()) {
            return null;
        }

        return value.trim()
                .toLowerCase(Locale.ROOT);
    }

    private String cleanPhone1(String value) {

        if (value == null || value.isBlank()) {
            return null;
        }

        return value
                .replace(" ", "")
                .replace("-", "")
                .trim();
    }

}